# Generated by Django 4.2 on 2024-01-04 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0006_team_uid'),
        ('leagues_event', '0009_leaguesevent_match_format_alter_leaguesevent_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.PositiveIntegerField()),
                ('team2', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False)),
                ('sets', models.ManyToManyField(to='matches.setscore')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_match', models.BooleanField(default=False)),
                ('leagues_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues_event.leaguesevent')),
                ('score', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.matchscore')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='teams.team')),
            ],
        ),
    ]
