# Generated by Django 4.2 on 2024-04-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
