# Generated by Django 4.2 on 2023-12-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
