# Generated by Django 4.2 on 2023-12-31 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
