# Generated by Django 4.2 on 2023-12-28 18:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaguesEvent',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('start_week', models.DateField()),
                ('end_week', models.DateField()),
                ('format', models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles'), ('mixed', 'Mixed')], max_length=10)),
                ('team_type', models.CharField(choices=[('team', 'Team'), ('individual', 'Individual')], max_length=15)),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('all', 'All')], max_length=10)),
                ('minimum_level', models.CharField(choices=[('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('5.5', '5.5'), ('6.0', '6.0')], max_length=10)),
                ('spots', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('inprogress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=15)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues_event.location')),
            ],
        ),
    ]
