# Generated by Django 4.2 on 2023-12-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues_event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='county',
            new_name='city',
        ),
    ]
