# Generated by Django 4.2 on 2023-12-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_members'),
        ('leagues_event', '0003_leaguesevent_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesevent',
            name='teams',
            field=models.ManyToManyField(related_name='events', to='teams.team'),
        ),
    ]
