# Generated by Django 4.2 on 2023-12-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_uid'),
        ('leagues_event', '0005_rename_spots_leaguesevent_total_spots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesevent',
            name='active_spots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguesevent',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='events', to='teams.team'),
        ),
    ]
