# Generated by Django 4.2 on 2024-01-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues_event', '0007_matchformat_remove_leaguesevent_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguesevent',
            name='match_format',
        ),
    ]
